---
- name: Configuración de prueba de Ansible Playbook
  hosts: localhost
  become: true

  tasks:
    - name: Instalar paquete tree
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: yes

    - name: Verificar instalación de tree
      shell: tree --version