---
- name: Configuración de prueba de Ansible Playbook
  hosts: localhost
  become: true

  tasks:
    - name: Instalar paquetes esenciales
      apt:
        name:
          - tree
        state: present
        update_cache: yes

    - name: Verificar instalación de tree
      shell: tree --version
