name: Ejercicio 1 - Shell Script

on:
  push:
    paths:
      - '.github/workflows/02-shell-script.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Dar permisos y ejecutar el script
        run: |
          chmod +x ejercicios/ejercicio1/script.sh
          ./ejercicios/ejercicio1/script.sh