name: 05-CI Básico Python

on:
  push:
    branches: [main, master, develop]
    paths:
      - '.github/workflows/05-app-python.yml'
      - '05-mi-app-python/**'
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r 05-mi-app-python/requirements.txt

    - name: Ejecutar tests
      run: |
        PYTHONPATH=05-mi-app-python pytest 05-mi-app-python/tests/ -v

    - name: Ejecutar con cobertura
      run: |
        PYTHONPATH=05-mi-app-python pytest --cov=05-mi-app-python/app.py --cov-report=term --cov-report=html 05-mi-app-python/tests/

    - name: Guardar reporte
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/

    - name: Verificar app corriendo
      run: |
        timeout 10 python 05-mi-app-python/app.py &
        sleep 5
        curl -f http://localhost:5000/health
