name: 10-Run Ansible Playbook
description: Run Ansible Playbook to deploy application

on:
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/10-ansible-playbook.yml'
      - '08-test-ansible-playbook/**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ansible Lint
      uses: ansible/ansible-lint@main

    - name: Run Ansible Lint
      run: |
        echo "Running Ansible Lint"
        ansible-lint 08-test-ansible-playbook/playbook.yml

  run-playbook:
    runs-on: self-hosted
    needs: ansible-lint

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook playbook.yml -i localhost, -c local